default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tlgbot_development

test:
  <<: *default
  database: tlgbot_test

production:
  <<: *default
  database: tlgbot_production
